### ISSUE TITLE
Sending minimal artifact using tfr release command 

### ISSUE THREAD

**Issue by Ravi-Gupta77** [geronimo-iia/terraform-aws-tf-registry-cli#5]
During the release of a given module into s3 bucket using tfr release command how can I control the generate artifacts (i.e exclude any file to be uploaded into s3 bucket)

**Comment by geronimo-iia** [comment]
Hello,

With the release command, you could specifiy the source folder with `-source`.

For now,  we prepare our artifacts outside of the python client, with something like that :

mkdir -p ${TERRAFORM_SOURCE}/target
find ${TERRAFORM_SOURCE}  -name '*.tf' -exec cp -prv '{}' '${TERRAFORM_SOURCE}/target' ';

tfr release --namespace ${DEFAULT_NAMESPACE} --name ${TERRAFORM_MODULE_NAME} --system ${TERRAFORM_SYSTEM} --version ${TERRAFORM_ARTIFACT_VERSION} --source ${TERRAFORM_SOURCE}/target

**Comment by Ravi-Gupta77** [comment]
Thank's 
It's working !

**Comment by Ravi-Gupta77** [comment]
Thank's
It's working !
