### ISSUE TITLE
Implementing AWS Cognito user pool for authentication 

### ISSUE THREAD

**Issue by Ravi-Gupta77** [geronimo-iia/terraform-aws-tf-registry-cli#6]
Instead of admin generating the JWT token for authentication to be used by end user how can Cognito user pool be used for authentication.

**Comment by geronimo-iia** [comment]
sorry for my late answer (few computer problem...)

We could use cognito to authenticate user, but it will be difficult to integrate this authentication method with terraform at the end. If you know a way to do that, let me known :) and after we could add few optional configuration in the registry module

Regards

Jerome

**Comment by Ravi-Gupta77** [comment]
For the past month, I have been working on integrating Cognito for a
private registry. I have successfully implemented Cognito, allowing the
registry to authenticate users and redirect them to a 'GET' method API
call. This API call invokes a Lambda function to generate access tokens
that can be used to download modules from Lambda authorizer-enabled API
endpoints.

Additionally, I've made some optimizations like instead of using python CLI
for releasing modules. I've implemented a GitHub action pipeline which can
also minimize artifacts. This pipeline should be included in the module to
be released.

Some code refactoring is yet to be completed & after that, I'll be sending
a PR for these additional configurations very soon along with an updated
architecture diagram.

Feel free to reach out if you have any queries.

Regards,
Ravi

**Comment by geronimo-iia** [comment]
Thanks a lot for your feedback, 

Python client is used outside github ci (where github action are just a wish/dream ...). We had done the very minimal stuff to be able to release something and manage jwt token.

Will be a pleasure to see how things goes with cognito and his integration with terraform/terragrunt.

Regards

Jerome
